### ISSUE TITLE
server开放ip是否可以以某种方式告知client?

### ISSUE THREAD

**Issue by defims** [qgy18/pangolin#5]
在vps上开启一个服务`pangolin server -p 10000`在本地｀pangolin client -r <public ip>:<port> -l <local http port>｀vps打印出`HTTPServer is running at port 10001`得到外部访问端口，这里每次都需要登录vps才能查看当前获得的访问端口是什么，是否可以在本地连接的时候就知道外网端口1001呢？这样server端可以持续运行

**Comment by qgy18** [comment]
我这边会显示啊。在本地执行：

``` bash
pangolin client -r xxx.xxx.xxx.xxx:10000 -l 9999

Connected to xxx.xxx.xxx.xxx 10001
Proxy pass to 127.0.0.1 9999
```

然后浏览器访问 http://xxx.xxx.xxx.xxx:10001 就可以了，不用去看 Server 的。

**Comment by qgy18** [comment]
修改了一下 client 端打印的信息，现在应该更明确了：

``` bash
pangolin client -r xxx.xxx.xxx.xxx:10000 -l 9999

Connected to xxx.xxx.xxx.xxx 10000
Proxy pass to 127.0.0.1 9999
Please visit http://xxx.xxx.xxx.xxx:10001
```

**Comment by defims** [comment]
看成是连接的端口了，修改后清晰，nice!
