### ISSUE TITLE
客户端连接远程服务端超时

### ISSUE THREAD

**Issue by bing0say** [qgy18/pangolin#8]
服务端信息：
TCPServer is running at port 10000 , accept 99 http clients
客户端信息：
Can not connect remote server! ETIMEDOUT
Remote server shutdown!

客户端连接使用的命令是：
pangolin client -r <domain>:<port> -l <port>

**Comment by qgy18** [comment]
你 telnet 一下 domain 和 port，类似这样：

```
telnet <your domain> 10000
```

我怀疑端口被屏蔽了。

**Comment by bing0say** [comment]
感谢，刚刚同事已经帮我在服务器打开了 10000 端口。
